export const topics = [
  {
    id: 'space',
    title: 'Space & Cosmos',
    emoji: '🚀',
    description: 'Explore the universe, planets, and beyond',
    color: '#4c1d95',
    questions: [
      {
        question: 'What is the largest planet in our solar system?',
        options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'],
        answer: 1,
        fact: 'Jupiter is so massive that more than 1,300 Earths could fit inside it!',
      },
      {
        question: 'How long does light from the Sun take to reach Earth?',
        options: ['8 seconds', '8 minutes', '8 hours', '8 days'],
        answer: 1,
        fact: 'Light travels at ~300,000 km/s. The Sun is ~150 million km away — about 8 minutes and 20 seconds.',
      },
      {
        question: 'What is a neutron star?',
        options: [
          'A young, hot star',
          'The collapsed core of a massive star',
          'A star with no nuclear reactions',
          'A binary star system',
        ],
        answer: 1,
        fact: 'Neutron stars are so dense that a teaspoon of their material would weigh about 10 million tonnes!',
      },
      {
        question: 'Which planet has the most moons (as of 2024)?',
        options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'],
        answer: 1,
        fact: 'Saturn has 146 confirmed moons — the most of any planet in our solar system.',
      },
      {
        question: 'What causes a solar eclipse?',
        options: [
          'Earth passes between the Sun and Moon',
          'Moon passes between the Sun and Earth',
          'Sun moves behind a nebula',
          "Earth's shadow falls on the Sun",
        ],
        answer: 1,
        fact: 'A total solar eclipse happens when the Moon perfectly covers the Sun — a cosmic coincidence because the Moon is ~400x smaller but ~400x closer.',
      },
    ],
  },
  {
    id: 'history',
    title: 'World History',
    emoji: '🏛️',
    description: 'Civilizations, empires, and turning points',
    color: '#92400e',
    questions: [
      {
        question: 'In what year did World War II end?',
        options: ['1943', '1944', '1945', '1946'],
        answer: 2,
        fact: 'WWII ended in 1945 — May 8 in Europe (V-E Day) and September 2 in the Pacific (V-J Day).',
      },
      {
        question: 'Which ancient wonder still stands today?',
        options: [
          'Colossus of Rhodes',
          'Great Pyramid of Giza',
          'Hanging Gardens of Babylon',
          'Lighthouse of Alexandria',
        ],
        answer: 1,
        fact: 'The Great Pyramid of Giza is the only ancient wonder still largely intact, built around 2560 BCE.',
      },
      {
        question: 'Who was the first woman to win a Nobel Prize?',
        options: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace', 'Florence Nightingale'],
        answer: 1,
        fact: 'Marie Curie won the Nobel Prize in Physics in 1903, and again in Chemistry in 1911 — the only person to win in two different sciences.',
      },
      {
        question: 'The Renaissance began in which country?',
        options: ['France', 'Greece', 'Italy', 'Spain'],
        answer: 2,
        fact: 'The Renaissance began in Italian city-states like Florence in the 14th century, sparked by a revival of classical learning.',
      },
      {
        question: 'Which empire was the largest in history by land area?',
        options: ['Roman Empire', 'Mongol Empire', 'British Empire', 'Ottoman Empire'],
        answer: 2,
        fact: 'The British Empire at its peak covered ~24% of Earth\'s land surface — about 35.5 million km².',
      },
    ],
  },
  {
    id: 'science',
    title: 'Science & Nature',
    emoji: '🔬',
    description: 'Biology, chemistry, and the natural world',
    color: '#065f46',
    questions: [
      {
        question: 'What is the powerhouse of the cell?',
        options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi apparatus'],
        answer: 1,
        fact: 'Mitochondria produce ATP through cellular respiration. They have their own DNA, suggesting they were once separate bacteria!',
      },
      {
        question: 'What is the chemical symbol for gold?',
        options: ['Go', 'Gd', 'Au', 'Ag'],
        answer: 2,
        fact: 'Au comes from the Latin "aurum." Gold is so rare that all the gold ever mined would fit in about 3.5 Olympic swimming pools.',
      },
      {
        question: 'How many bones does an adult human have?',
        options: ['186', '206', '226', '246'],
        answer: 1,
        fact: 'Adults have 206 bones, but babies are born with ~270. Many fuse together as we grow.',
      },
      {
        question: 'What is the speed of light in a vacuum?',
        options: [
          '300,000 km/s',
          '150,000 km/s',
          '450,000 km/s',
          '30,000 km/s',
        ],
        answer: 0,
        fact: 'Light travels at exactly 299,792,458 m/s in a vacuum — used to define the metre itself!',
      },
      {
        question: 'Which element has the highest melting point?',
        options: ['Iron', 'Carbon', 'Tungsten', 'Platinum'],
        answer: 2,
        fact: 'Tungsten melts at 3,422°C — the highest of all pure metals. That\'s why it\'s used in light bulb filaments.',
      },
    ],
  },
  {
    id: 'tech',
    title: 'Technology',
    emoji: '💻',
    description: 'Computers, AI, and digital innovation',
    color: '#0c4a6e',
    questions: [
      {
        question: 'Who is credited with inventing the World Wide Web?',
        options: ['Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Vint Cerf'],
        answer: 1,
        fact: 'Tim Berners-Lee invented the WWW in 1989 at CERN. He deliberately made it royalty-free to allow it to flourish.',
      },
      {
        question: 'What does "CPU" stand for?',
        options: [
          'Central Processing Unit',
          'Computer Processing Utility',
          'Core Power Unit',
          'Central Program Utility',
        ],
        answer: 0,
        fact: 'The CPU is the brain of a computer. Modern CPUs can perform billions of operations per second.',
      },
      {
        question: 'What programming language was created by Guido van Rossum?',
        options: ['Java', 'Ruby', 'Python', 'C++'],
        answer: 2,
        fact: 'Python was released in 1991. Guido named it after Monty Python\'s Flying Circus, not the snake.',
      },
      {
        question: 'What does "AI" stand for in the context of computing?',
        options: [
          'Automated Intelligence',
          'Artificial Intelligence',
          'Advanced Integration',
          'Algorithmic Interface',
        ],
        answer: 1,
        fact: 'The term "Artificial Intelligence" was coined by John McCarthy in 1956 at the Dartmouth Conference.',
      },
      {
        question: 'Which company developed the Android operating system?',
        options: ['Apple', 'Microsoft', 'Samsung', 'Google'],
        answer: 3,
        fact: 'Android Inc. was founded in 2003 and acquired by Google in 2005. It\'s now the world\'s most used mobile OS.',
      },
    ],
  },
  {
    id: 'geography',
    title: 'World Geography',
    emoji: '🌍',
    description: 'Countries, capitals, and landscapes',
    color: '#1e3a5f',
    questions: [
      {
        question: 'What is the longest river in the world?',
        options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
        answer: 1,
        fact: 'The Nile is ~6,650 km long. However, some studies argue the Amazon may be slightly longer when its full source is measured.',
      },
      {
        question: 'Which country has the most natural lakes?',
        options: ['Russia', 'USA', 'Canada', 'Finland'],
        answer: 2,
        fact: 'Canada has over 2 million lakes — more than all other countries combined. They cover about 9% of its land area.',
      },
      {
        question: 'What is the smallest country in the world?',
        options: ['Monaco', 'San Marino', 'Vatican City', 'Liechtenstein'],
        answer: 2,
        fact: 'Vatican City covers just 0.44 km² within Rome and has a population of about 800 people.',
      },
      {
        question: 'The Amazon Rainforest spans how many countries?',
        options: ['4', '6', '9', '12'],
        answer: 2,
        fact: 'The Amazon spans 9 countries: Brazil, Peru, Colombia, Venezuela, Ecuador, Bolivia, Guyana, Suriname, and French Guiana.',
      },
      {
        question: 'Which ocean is the largest?',
        options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
        answer: 3,
        fact: 'The Pacific Ocean covers more area than all the Earth\'s land masses combined — about 165 million km².',
      },
    ],
  },
  {
    id: 'art',
    title: 'Art & Culture',
    emoji: '🎨',
    description: 'Art, music, literature, and creativity',
    color: '#7e1d7e',
    questions: [
      {
        question: 'Who painted the Mona Lisa?',
        options: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Caravaggio'],
        answer: 2,
        fact: 'Leonardo da Vinci painted the Mona Lisa between 1503–1519. It\'s the most visited artwork in the world at the Louvre.',
      },
      {
        question: 'Which composer was deaf when he wrote his 9th Symphony?',
        options: ['Mozart', 'Bach', 'Beethoven', 'Chopin'],
        answer: 2,
        fact: 'Beethoven was almost completely deaf when he composed his legendary 9th Symphony in 1824.',
      },
      {
        question: 'Who wrote the novel "Pride and Prejudice"?',
        options: ['Charlotte Brontë', 'Jane Austen', 'George Eliot', 'Mary Shelley'],
        answer: 1,
        fact: 'Jane Austen published "Pride and Prejudice" in 1813. It opens with one of literature\'s most famous lines.',
      },
      {
        question: 'What art movement is Salvador Dalí associated with?',
        options: ['Impressionism', 'Cubism', 'Surrealism', 'Expressionism'],
        answer: 2,
        fact: 'Surrealism explored the unconscious mind through dreamlike, bizarre imagery. Dalí\'s melting clocks are iconic.',
      },
      {
        question: 'In which city is the Louvre Museum located?',
        options: ['Rome', 'London', 'Paris', 'Madrid'],
        answer: 2,
        fact: 'The Louvre in Paris is the world\'s largest art museum, attracting ~9 million visitors per year.',
      },
    ],
  },
]
